CREATE DATABASE M_Roman;

USE M_Roman;

CREATE TABLE Professores(
	IdProfessor INT PRIMARY KEY IDENTITY,
	Nome VARCHAR(255) NOT NULL,
	Email VARCHAR(255) UNIQUE NOT NULL,
	Senha VARCHAR(255) NOT NULL,
);

CREATE TABLE Temas(
	IdTema INT PRIMARY KEY IDENTITY,
	Nome VARCHAR(255) NOT NULL UNIQUE,
);


CREATE TABLE Projetos(
	IdProjeto INT PRIMARY KEY IDENTITY,
	IdProfessor INT FOREIGN KEY REFERENCES Professores(IdProfessor),
	IdTema INT FOREIGN KEY REFERENCES Temas(IdTema),
	Nome VARCHAR(255) NOT NULL,
);

